version: '3.8'

services:

  frontend:
    build: stock-dashboard-project-frontend:latest

  backend:
    build: stock-dashboard-project-backend:latest

  redis:
    image: redis:alpine

  mongo:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db

  nginx:
    image: nginx:alpine
    ports:
      - "3000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend

volumes:
  mongo-data: